# -*- coding: utf-8 -*-
"""P1HW1_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jT1ok755nIatlwhB2av2ixR2mQ4Ff8D
"""

print("-----Calculating Exponents-----")
print("")

num_1 = int(input("Enter an integer as the base value: "))
num_2 = int(input("Enter an integer as the exponent: "))
print("")

print(num_1, "to the power of", num_2, "is equal to", num_1**num_2, "!!!")
print("")

print("-----Addition and Subtraction-----")
print("")
num_3 = int(input("Enter a starting integer: "))
num_4 = int(input("Enter an integer to add: "))
num_5 = int(input("Enter an integer to subtract: "))

print(num_3, "+", num_4, "-", num_5, "is equal to", num_3+num_4-num_5, "!!!")

